"""add client settlement status

Revision ID: 5e8fe98cd2f4
Revises: 
Create Date: 2025-05-27 11:25:31.472313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e8fe98cd2f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('payments', sa.Column('client_settlement_status', sa.Enum('PENDING', 'SETTLED', name='clientsettlementstatus'), nullable=False))
    op.add_column('payments', sa.Column(
        'client_settlement_status',
        sa.Enum('PENDING', 'SETTLED', name='clientsettlementstatus'),
        nullable=False,
        server_default='PENDING'
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'client_settlement_status')
    # ### end Alembic commands ###
